version: "3.9"
services:
  proxy:
    #コンテナの名前
    container_name: kchat-proxy
    #dockerfileの場所
    build: ./docker/nginx
    #ホスト(PC)のゲスト(コンテナ)のポートを紐づけ
    #{ホスト}:{ゲスト}
    ports:
      - "8000:80"
    #ホストのディレクトリとゲストのディレクトリの紐づけ(同期)
    volumes:
      #ngixの設定ファイルは/etc/nginx/conf.d/default.confに置く
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
      #ngixのドキュメントルートは/usr/share/nginx/html固定
      - ./src:/usr/share/nginx/html
  app:
    #コンテナの名前
    container_name: kchat-app
    #dockerfileの場所
    build: ./docker/php
    volumes:
     - ./docker/php/php.ini:/usr/local/php/php.ini
    #phpコンテナ内のドキュメントルートは/var/www/html 
     - ./src/:/var/www/html 
  db:
    container_name: kchat-db
    build: ./docker/mysql
    ports:
      - 3306:3306
    volumes:
      - ./docker/mysql/my.cnf:/etc/mysql/my.cnf
      - fullstack-db-volume:/var/lib/mysql
    environment:
      MYSQL_DATABASE: kchat_db
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_USER: user
      MYSQL_PASSWORD: password
  phpmyadmin:
    container_name: fullstack-phpmyadmin
    image: phpmyadmin/phpmyadmin
    ports:
      - 8001:80
    environment:
      - PMA_ARBITRARY=1
      - PMA_HOST=db
      - PMA_ROOT_PASSWORD=rootpassword
volumes:
  fullstack-db-volume:

  